version: "3.8"

services:
    app:
        build:
            context: .
        environment:
            - PORT=${PORT}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
            - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
            - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
            - FACEBOOK_CALLBACK_URL=${FACEBOOK_CALLBACK_URL}
            - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
            - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
            - GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}
            - FRONTEND_URL=${FRONTEND_URL}
            - MONGODB_URI=${MONGODB_URI}
            - SESSIONSDB_URI=${SESSIONSDB_URI}
            - EMAIL=${EMAIL}
            - PASSWORD=${PASSWORD}
            - SECRET=${SECRET}
            - JWT_EXPIRATION=${JWT_EXPIRATION}
            - CLOUDINARY_URL=${CLOUDINARY_URL}
        ports:
            - "3001:3001"
